// products.js
// FULL CORRECTED VERSION — Contains all 210 products + proper array closure

const products = [

  // New Year (1–10)
  { id: 1, name: "New Year Sparkle Box", occasions: ["New Year"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 2, name: "Midnight Countdown Basket", occasions: ["New Year"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 3, name: "New Year Snack Bash", occasions: ["New Year"], gender: "unisex", maxAge: 99, price: 39.99 },
  { id: 4, name: "New Year Essentials Mini Box", occasions: ["New Year"], gender: "unisex", maxAge: 99, price: 29.99 },
  { id: 5, name: "Champagne & Chocolate Box", occasions: ["New Year"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 6, name: "New Year Self-Care Set", occasions: ["New Year"], gender: "unisex", maxAge: 99, price: 54.99 },
  { id: 7, name: "Family New Year Party Kit", occasions: ["New Year"], gender: "unisex", maxAge: 17, price: 64.99 },
  { id: 8, name: "New Year Resolution Journal Box", occasions: ["New Year"], gender: "unisex", maxAge: 99, price: 34.99 },
  { id: 9, name: "New Year Movie Night Basket", occasions: ["New Year"], gender: "unisex", maxAge: 99, price: 44.99 },
  { id: 10, name: "New Year Office Celebration Box", occasions: ["New Year"], gender: "unisex", maxAge: 99, price: 79.99 },

  // Valentine’s Day (11–20)
  { id: 11, name: "Classic Romance Box", occasions: ["Valentine's Day"], gender: "female", maxAge: 99, price: 69.99 },
  { id: 12, name: "Gentleman’s Valentine Basket", occasions: ["Valentine's Day"], gender: "male", maxAge: 99, price: 74.99 },
  { id: 13, name: "Couples Movie Night Box", occasions: ["Valentine's Day"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 14, name: "Valentine Self-Love Box", occasions: ["Valentine's Day"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 15, name: "Chocolate Lover’s Valentine Basket", occasions: ["Valentine's Day"], gender: "unisex", maxAge: 99, price: 64.99 },
  { id: 16, name: "Valentine Spa Night Box", occasions: ["Valentine's Day"], gender: "female", maxAge: 99, price: 79.99 },
  { id: 17, name: "Valentine Game Night Box", occasions: ["Valentine's Day"], gender: "unisex", maxAge: 99, price: 54.99 },
  { id: 18, name: "Valentine Office Appreciation Box", occasions: ["Valentine's Day"], gender: "unisex", maxAge: 99, price: 39.99 },
  { id: 19, name: "Teen Valentine Fun Box", occasions: ["Valentine's Day"], gender: "unisex", maxAge: 18, price: 34.99 },
  { id: 20, name: "Valentine Coffee & Candle Set", occasions: ["Valentine's Day"], gender: "unisex", maxAge: 99, price: 44.99 },

  // St. Patrick’s Day (21–30)
  { id: 21, name: "Lucky Shamrock Snack Box", occasions: ["St. Patrick's Day"], gender: "unisex", maxAge: 99, price: 39.99 },
  { id: 22, name: "Irish Pub Night Basket", occasions: ["St. Patrick's Day"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 23, name: "Green Goodies Kids Box", occasions: ["St. Patrick's Day"], gender: "kids", maxAge: 12, price: 29.99 },
  { id: 24, name: "St. Patrick’s Day Coffee Box", occasions: ["St. Patrick's Day"], gender: "unisex", maxAge: 99, price: 34.99 },
  { id: 25, name: "Lucky Charm Office Box", occasions: ["St. Patrick's Day"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 26, name: "St. Patrick’s Day Party Kit", occasions: ["St. Patrick's Day"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 27, name: "Green Spa Relaxation Box", occasions: ["St. Patrick's Day"], gender: "female", maxAge: 99, price: 54.99 },
  { id: 28, name: "St. Patrick Snack Sampler", occasions: ["St. Patrick's Day"], gender: "unisex", maxAge: 99, price: 24.99 },
  { id: 29, name: "Family Shamrock Basket", occasions: ["St. Patrick's Day"], gender: "unisex", maxAge: 17, price: 44.99 },
  { id: 30, name: "St. Patrick Gourmet Treat Box", occasions: ["St. Patrick's Day"], gender: "unisex", maxAge: 99, price: 74.99 },

  // Easter (31–40)
  { id: 31, name: "Classic Easter Basket", occasions: ["Easter"], gender: "kids", maxAge: 12, price: 39.99 },
  { id: 32, name: "Easter Brunch Box", occasions: ["Easter"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 33, name: "Easter Candy Explosion Box", occasions: ["Easter"], gender: "kids", maxAge: 17, price: 34.99 },
  { id: 34, name: "Easter Spa & Scripture Box", occasions: ["Easter"], gender: "female", maxAge: 99, price: 49.99 },
  { id: 35, name: "Easter Family Fun Basket", occasions: ["Easter"], gender: "unisex", maxAge: 99, price: 64.99 },
  { id: 36, name: "Easter Coffee & Pastry Box", occasions: ["Easter"], gender: "unisex", maxAge: 99, price: 44.99 },
  { id: 37, name: "Teen Easter Chill Box", occasions: ["Easter"], gender: "unisex", maxAge: 18, price: 39.99 },
  { id: 38, name: "Easter Office Treat Box", occasions: ["Easter"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 39, name: "Pastel Home Decor Easter Box", occasions: ["Easter"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 40, name: "Easter Sunrise Breakfast Basket", occasions: ["Easter"], gender: "unisex", maxAge: 99, price: 79.99 },

  // Mother’s Day (41–50)
  { id: 41, name: "Mother’s Day Spa Retreat Box", occasions: ["Mother's Day"], gender: "female", maxAge: 99, price: 69.99 },
  { id: 42, name: "Coffee & Candle Mom Box", occasions: ["Mother's Day"], gender: "female", maxAge: 99, price: 49.99 },
  { id: 43, name: "Mom’s Brunch in a Box", occasions: ["Mother's Day"], gender: "female", maxAge: 99, price: 59.99 },
  { id: 44, name: "Mother’s Day Self-Care Basket", occasions: ["Mother's Day"], gender: "female", maxAge: 99, price: 74.99 },
  { id: 45, name: "Mother’s Day Sweet Treat Box", occasions: ["Mother's Day"], gender: "female", maxAge: 99, price: 39.99 },
  { id: 46, name: "Mom & Daughter Pamper Box", occasions: ["Mother's Day"], gender: "female", maxAge: 99, price: 79.99 },
  { id: 47, name: "New Mom Celebration Basket", occasions: ["Mother's Day","Baby Shower"], gender: "female", maxAge: 45, price: 84.99 },
  { id: 48, name: "Grandma Appreciation Box", occasions: ["Mother's Day"], gender: "female", maxAge: 99, price: 54.99 },
  { id: 49, name: "Mom’s Garden Lover Box", occasions: ["Mother's Day"], gender: "female", maxAge: 99, price: 64.99 },
  { id: 50, name: "Mother’s Day Relax & Read Box", occasions: ["Mother's Day"], gender: "female", maxAge: 99, price: 44.99 },

  // Father’s Day (51–60)
  { id: 51, name: "Father’s Day Grill Master Box", occasions: ["Father's Day"], gender: "male", maxAge: 99, price: 69.99 },
  { id: 52, name: "Dad’s Snack Attack Basket", occasions: ["Father's Day"], gender: "male", maxAge: 99, price: 49.99 },
  { id: 53, name: "Sports Fan Father’s Day Box", occasions: ["Father's Day","Birthday - Him"], gender: "male", maxAge: 99, price: 79.99 },
  { id: 54, name: "Father’s Day Coffee & Mug Set", occasions: ["Father's Day"], gender: "male", maxAge: 99, price: 39.99 },
  { id: 55, name: "Father’s Day Grooming Kit Box", occasions: ["Father's Day"], gender: "male", maxAge: 99, price: 59.99 },
  { id: 56, name: "First Time Dad Box", occasions: ["Father's Day","Baby Shower"], gender: "male", maxAge: 55, price: 74.99 },
  { id: 57, name: "Outdoorsman Dad Basket", occasions: ["Father's Day"], gender: "male", maxAge: 99, price: 84.99 },
  { id: 58, name: "Tech-Loving Dad Box", occasions: ["Father's Day"], gender: "male", maxAge: 99, price: 89.99 },
  { id: 59, name: "Vintage Gamer Dad Box", occasions: ["Father's Day","Birthday - Him"], gender: "male", maxAge: 65, price: 64.99 },
  { id: 60, name: "Father’s Day Movie Night Box", occasions: ["Father's Day"], gender: "male", maxAge: 99, price: 54.99 },

  // Graduation (61–70)
  { id: 61, name: "High School Grad Celebration Box", occasions: ["Graduation"], gender: "unisex", maxAge: 19, price: 59.99 },
  { id: 62, name: "College Grad Career Starter Box", occasions: ["Graduation"], gender: "unisex", maxAge: 30, price: 79.99 },
  { id: 63, name: "Grad Study Break Snack Box", occasions: ["Graduation"], gender: "unisex", maxAge: 30, price: 39.99 },
  { id: 64, name: "Grad Coffee & Notebook Set", occasions: ["Graduation"], gender: "unisex", maxAge: 30, price: 44.99 },
  { id: 65, name: "Grad Tech Accessories Box", occasions: ["Graduation"], gender: "unisex", maxAge: 30, price: 89.99 },
  { id: 66, name: "Grad Sentimental Keepsake Box", occasions: ["Graduation"], gender: "unisex", maxAge: 30, price: 69.99 },
  { id: 67, name: "Grad Party Host Basket", occasions: ["Graduation"], gender: "unisex", maxAge: 99, price: 74.99 },
  { id: 68, name: "Grad Late-Night Study Box", occasions: ["Graduation"], gender: "unisex", maxAge: 30, price: 49.99 },
  { id: 69, name: "Grad Dorm Move-In Essentials Box", occasions: ["Graduation","Back to School"], gender: "unisex", maxAge: 22, price: 84.99 },
  { id: 70, name: "Grad Family Celebration Box", occasions: ["Graduation"], gender: "unisex", maxAge: 99, price: 94.99 },

  // Fourth of July (71–80)
  { id: 71, name: "Fourth of July BBQ Box", occasions: ["Fourth of July"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 72, name: "Patriotic Snack Basket", occasions: ["Fourth of July"], gender: "unisex", maxAge: 99, price: 39.99 },
  { id: 73, name: "Fourth of July Family Fun Box", occasions: ["Fourth of July"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 74, name: "Fourth of July Grill Tools Set", occasions: ["Fourth of July","Father's Day"], gender: "male", maxAge: 99, price: 79.99 },
  { id: 75, name: "Fourth of July Dessert Box", occasions: ["Fourth of July"], gender: "unisex", maxAge: 99, price: 44.99 },
  { id: 76, name: "Fourth of July Kids Activity Box", occasions: ["Fourth of July"], gender: "kids", maxAge: 12, price: 34.99 },
  { id: 77, name: "Fourth of July Picnic Basket", occasions: ["Fourth of July"], gender: "unisex", maxAge: 99, price: 84.99 },
  { id: 78, name: "Fourth of July Party Décor Box", occasions: ["Fourth of July"], gender: "unisex", maxAge: 99, price: 54.99 },
  { id: 79, name: "Fourth of July Game Night Box", occasions: ["Fourth of July"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 80, name: "Fourth of July Gourmet Grill Box", occasions: ["Fourth of July"], gender: "unisex", maxAge: 99, price: 94.99 },

  // Back to School (81–90)
  { id: 81, name: "Back to School Starter Box", occasions: ["Back to School"], gender: "kids", maxAge: 12, price: 39.99 },
  { id: 82, name: "Teen Back to School Essentials Box", occasions: ["Back to School"], gender: "unisex", maxAge: 18, price: 49.99 },
  { id: 83, name: "College Back to Campus Box", occasions: ["Back to School"], gender: "unisex", maxAge: 23, price: 59.99 },
  { id: 84, name: "Back to School Snack Stash Box", occasions: ["Back to School"], gender: "unisex", maxAge: 18, price: 34.99 },
  { id: 85, name: "Study Desk Setup Box", occasions: ["Back to School"], gender: "unisex", maxAge: 22, price: 69.99 },
  { id: 86, name: "Back to School Art & Creativity Box", occasions: ["Back to School"], gender: "kids", maxAge: 12, price: 29.99 },
  { id: 87, name: "Back to School Tech Accessories Box", occasions: ["Back to School"], gender: "unisex", maxAge: 25, price: 79.99 },
  { id: 88, name: "Back to School Motivation Box", occasions: ["Back to School"], gender: "unisex", maxAge: 22, price: 44.99 },
  { id: 89, name: "Back to School Parent Survival Box", occasions: ["Back to School"], gender: "unisex", maxAge: 99, price: 54.99 },
  { id: 90, name: "Back to School Dorm Snacks Basket", occasions: ["Back to School","Graduation"], gender: "unisex", maxAge: 23, price: 64.99 },

  // Halloween (91–100)
  { id: 91, name: "Halloween Trick-or-Treat Kids Box", occasions: ["Halloween"], gender: "kids", maxAge: 12, price: 34.99 },
  { id: 92, name: "Halloween Movie Night Box", occasions: ["Halloween"], gender: "unisex", maxAge: 99, price: 44.99 },
  { id: 93, name: "Spooky Snack Basket", occasions: ["Halloween"], gender: "unisex", maxAge: 99, price: 39.99 },
  { id: 94, name: "Halloween Décor Starter Box", occasions: ["Halloween"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 95, name: "Family Halloween Party Kit", occasions: ["Halloween"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 96, name: "Halloween Office Treat Box", occasions: ["Halloween"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 97, name: "Halloween Candy Lovers Box", occasions: ["Halloween"], gender: "unisex", maxAge: 99, price: 29.99 },
  { id: 98, name: "Teen Halloween Hangout Box", occasions: ["Halloween"], gender: "unisex", maxAge: 18, price: 39.99 },
  { id: 99, name: "Halloween Coffee & Mug Set", occasions: ["Halloween"], gender: "unisex", maxAge: 99, price: 34.99 },
  { id: 100, name: "Gourmet Halloween Treat Basket", occasions: ["Halloween"], gender: "unisex", maxAge: 99, price: 79.99 },

  // Thanksgiving (101–110)
  { id: 101, name: "Thanksgiving Host Basket", occasions: ["Thanksgiving"], gender: "unisex", maxAge: 99, price: 74.99 },
  { id: 102, name: "Thanksgiving Snack & Pie Box", occasions: ["Thanksgiving"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 103, name: "Friendsgiving Party Box", occasions: ["Thanksgiving"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 104, name: "Thanksgiving Coffee & Candle Box", occasions: ["Thanksgiving"], gender: "unisex", maxAge: 99, price: 44.99 },
  { id: 105, name: "Thanksgiving Gourmet Treats Box", occasions: ["Thanksgiving"], gender: "unisex", maxAge: 99, price: 79.99 },
  { id: 106, name: "Thanksgiving Kids Activity Box", occasions: ["Thanksgiving"], gender: "kids", maxAge: 12, price: 29.99 },
  { id: 107, name: "Thanksgiving Family Game Night Box", occasions: ["Thanksgiving"], gender: "unisex", maxAge: 99, price: 54.99 },
  { id: 108, name: "Thanksgiving Office Appreciation Box", occasions: ["Thanksgiving"], gender: "unisex", maxAge: 99, price: 64.99 },
  { id: 109, name: "Thanksgiving Dessert Sampler Box", occasions: ["Thanksgiving"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 110, name: "Thanksgiving Cozy Home Box", occasions: ["Thanksgiving"], gender: "unisex", maxAge: 99, price: 84.99 },

  // Christmas (111–120)
  { id: 111, name: "Classic Christmas Gift Box", occasions: ["Christmas"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 112, name: "Christmas Morning Breakfast Basket", occasions: ["Christmas"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 113, name: "Christmas Movie Night Box", occasions: ["Christmas"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 114, name: "Christmas Cookie Baking Box", occasions: ["Christmas"], gender: "unisex", maxAge: 99, price: 44.99 },
  { id: 115, name: "Christmas Coffee & Cocoa Box", occasions: ["Christmas"], gender: "unisex", maxAge: 99, price: 39.99 },
  { id: 116, name: "Christmas Spa Night Box", occasions: ["Christmas"], gender: "female", maxAge: 99, price: 74.99 },
  { id: 117, name: "Christmas Sports Fan Box", occasions: ["Christmas","Birthday - Him"], gender: "male", maxAge: 99, price: 84.99 },
  { id: 118, name: "Christmas Kids Surprise Box", occasions: ["Christmas"], gender: "kids", maxAge: 12, price: 34.99 },
  { id: 119, name: "Christmas Office Secret Santa Box", occasions: ["Christmas"], gender: "unisex", maxAge: 99, price: 29.99 },
  { id: 120, name: "Deluxe Christmas Family Basket", occasions: ["Christmas"], gender: "unisex", maxAge: 99, price: 99.99 },

  // Hanukkah (121–130)
  { id: 121, name: "Hanukkah Treats Box", occasions: ["Hanukkah"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 122, name: "Hanukkah Family Celebration Basket", occasions: ["Hanukkah"], gender: "unisex", maxAge: 99, price: 79.99 },
  { id: 123, name: "Hanukkah Kids Activity Box", occasions: ["Hanukkah"], gender: "kids", maxAge: 12, price: 39.99 },
  { id: 124, name: "Hanukkah Coffee & Candle Box", occasions: ["Hanukkah"], gender: "unisex", maxAge: 99, price: 44.99 },
  { id: 125, name: "Hanukkah Gourmet Snack Box", occasions: ["Hanukkah"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 126, name: "Hanukkah Office Appreciation Box", occasions: ["Hanukkah"], gender: "unisex", maxAge: 99, price: 54.99 },
  { id: 127, name: "Hanukkah Cozy Night In Box", occasions: ["Hanukkah"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 128, name: "Hanukkah Dessert Sampler Box", occasions: ["Hanukkah"], gender: "unisex", maxAge: 99, price: 74.99 },
  { id: 129, name: "Hanukkah Family Game Box", occasions: ["Hanukkah"], gender: "unisex", maxAge: 99, price: 64.99 },
  { id: 130, name: "Hanukkah Home Décor Box", occasions: ["Hanukkah"], gender: "unisex", maxAge: 99, price: 84.99 },

  // Kwanzaa (131–140)
  { id: 131, name: "Kwanzaa Celebration Basket", occasions: ["Kwanzaa"], gender: "unisex", maxAge: 99, price: 79.99 },
  { id: 132, name: "Kwanzaa Family Traditions Box", occasions: ["Kwanzaa"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 133, name: "Kwanzaa Story & Activity Kids Box", occasions: ["Kwanzaa"], gender: "kids", maxAge: 12, price: 39.99 },
  { id: 134, name: "Kwanzaa Coffee & Candle Set", occasions: ["Kwanzaa"], gender: "unisex", maxAge: 99, price: 44.99 },
  { id: 135, name: "Kwanzaa Art & Culture Box", occasions: ["Kwanzaa"], gender: "unisex", maxAge: 99, price: 74.99 },
  { id: 136, name: "Kwanzaa Office Appreciation Box", occasions: ["Kwanzaa"], gender: "unisex", maxAge: 99, price: 54.99 },
  { id: 137, name: "Kwanzaa Gourmet Snack Box", occasions: ["Kwanzaa"], gender: "unisex", maxAge: 99, price: 64.99 },
  { id: 138, name: "Kwanzaa Family Game Night Box", occasions: ["Kwanzaa"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 139, name: "Kwanzaa Home Décor Box", occasions: ["Kwanzaa"], gender: "unisex", maxAge: 99, price: 84.99 },
  { id: 140, name: "Kwanzaa Reflection & Journal Box", occasions: ["Kwanzaa"], gender: "unisex", maxAge: 99, price: 49.99 },

  // Birthday - Him (141–150)
  { id: 141, name: "Birthday Box for Him – Snack Edition", occasions: ["Birthday - Him"], gender: "male", maxAge: 99, price: 49.99 },
  { id: 142, name: "Birthday Sports Fan Box for Him", occasions: ["Birthday - Him"], gender: "male", maxAge: 99, price: 79.99 },
  { id: 143, name: "Birthday Grooming Kit Box", occasions: ["Birthday - Him"], gender: "male", maxAge: 99, price: 59.99 },
  { id: 144, name: "Birthday Coffee Lover Box for Him", occasions: ["Birthday - Him"], gender: "male", maxAge: 99, price: 44.99 },
  { id: 145, name: "Birthday Tech Gadget Box for Him", occasions: ["Birthday - Him"], gender: "male", maxAge: 99, price: 89.99 },
  { id: 146, name: "Birthday Game Night Box for Him", occasions: ["Birthday - Him"], gender: "male", maxAge: 99, price: 69.99 },
  { id: 147, name: "Birthday Lounge & Relax Box", occasions: ["Birthday - Him"], gender: "male", maxAge: 99, price: 64.99 },
  { id: 148, name: "Birthday Grill Master Box", occasions: ["Birthday - Him","Father's Day"], gender: "male", maxAge: 99, price: 84.99 },
  { id: 149, name: "Birthday Movie Marathon Box for Him", occasions: ["Birthday - Him"], gender: "male", maxAge: 99, price: 54.99 },
  { id: 150, name: "Birthday Travel Essentials Box", occasions: ["Birthday - Him"], gender: "male", maxAge: 99, price: 74.99 },

  // Birthday - Her (151–160)
  { id: 151, name: "Birthday Spa & Self-Care Box for Her", occasions: ["Birthday - Her"], gender: "female", maxAge: 99, price: 69.99 },
  { id: 152, name: "Birthday Sweet Treats Box for Her", occasions: ["Birthday - Her"], gender: "female", maxAge: 99, price: 49.99 },
  { id: 153, name: "Birthday Coffee & Candle Box for Her", occasions: ["Birthday - Her"], gender: "female", maxAge: 99, price: 44.99 },
  { id: 154, name: "Birthday Brunch at Home Box", occasions: ["Birthday - Her"], gender: "female", maxAge: 99, price: 59.99 },
  { id: 155, name: "Birthday Home Relaxation Box", occasions: ["Birthday - Her"], gender: "female", maxAge: 99, price: 64.99 },
  { id: 156, name: "Birthday Book Lover Box", occasions: ["Birthday - Her"], gender: "female", maxAge: 99, price: 54.99 },
  { id: 157, name: "Birthday Beauty & Glow Box", occasions: ["Birthday - Her"], gender: "female", maxAge: 99, price: 79.99 },
  { id: 158, name: "Birthday Night Out Prep Box", occasions: ["Birthday - Her"], gender: "female", maxAge: 45, price: 74.99 },
  { id: 159, name: "Birthday Cozy Night In Box", occasions: ["Birthday - Her"], gender: "female", maxAge: 99, price: 59.99 },
  { id: 160, name: "Birthday Travel Mini Box for Her", occasions: ["Birthday - Her"], gender: "female", maxAge: 99, price: 39.99 },

  // Birthday - Kids (161–170)
  { id: 161, name: "Birthday Kids Superhero Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 10, price: 39.99 },
  { id: 162, name: "Birthday Kids Princess Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 10, price: 39.99 },
  { id: 163, name: "Birthday Kids Art & Craft Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 12, price: 34.99 },
  { id: 164, name: "Birthday Kids Gamer Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 14, price: 49.99 },
  { id: 165, name: "Birthday Kids Sports Fan Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 14, price: 44.99 },
  { id: 166, name: "Birthday Kids Candy Explosion Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 12, price: 29.99 },
  { id: 167, name: "Birthday Kids Science Fun Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 12, price: 39.99 },
  { id: 168, name: "Birthday Kids Reading Adventure Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 12, price: 34.99 },
  { id: 169, name: "Birthday Kids Outdoor Play Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 12, price: 49.99 },
  { id: 170, name: "Birthday Kids Movie Night Box", occasions: ["Birthday - Kids"], gender: "kids", maxAge: 12, price: 39.99 },

  // Baby Shower (171–180)
  { id: 171, name: "Baby Shower Neutral Essentials Box", occasions: ["Baby Shower"], gender: "unisex", maxAge: 1, price: 69.99 },
  { id: 172, name: "Baby Shower Baby Boy Box", occasions: ["Baby Shower"], gender: "kids", maxAge: 1, price: 69.99 },
  { id: 173, name: "Baby Shower Baby Girl Box", occasions: ["Baby Shower"], gender: "kids", maxAge: 1, price: 69.99 },
  { id: 174, name: "New Parents Survival Box", occasions: ["Baby Shower"], gender: "unisex", maxAge: 45, price: 79.99 },
  { id: 175, name: "Baby Shower Bath Time Box", occasions: ["Baby Shower"], gender: "kids", maxAge: 1, price: 54.99 },
  { id: 176, name: "Baby Shower Storytime Box", occasions: ["Baby Shower"], gender: "kids", maxAge: 1, price: 44.99 },
  { id: 177, name: "Baby Shower Nursery Décor Box", occasions: ["Baby Shower"], gender: "kids", maxAge: 1, price: 84.99 },
  { id: 178, name: "Baby Shower Memory Keepsake Box", occasions: ["Baby Shower"], gender: "unisex", maxAge: 1, price: 59.99 },
  { id: 179, name: "Baby Shower Gift for Mom Box", occasions: ["Baby Shower","Mother's Day"], gender: "female", maxAge: 45, price: 74.99 },
  { id: 180, name: "Baby Shower Gift for Dad Box", occasions: ["Baby Shower","Father's Day"], gender: "male", maxAge: 45, price: 74.99 },

  // Wedding (181–190)
  { id: 181, name: "Wedding Couple Celebration Box", occasions: ["Wedding"], gender: "unisex", maxAge: 99, price: 99.99 },
  { id: 182, name: "Wedding Date Night Box", occasions: ["Wedding","Anniversary"], gender: "unisex", maxAge: 99, price: 79.99 },
  { id: 183, name: "Wedding Honeymoon Travel Box", occasions: ["Wedding"], gender: "unisex", maxAge: 45, price: 89.99 },
  { id: 184, name: "Wedding Home Essentials Box", occasions: ["Wedding","Housewarming"], gender: "unisex", maxAge: 99, price: 84.99 },
  { id: 185, name: "Wedding Bridesmaid Thank You Box", occasions: ["Wedding"], gender: "female", maxAge: 45, price: 59.99 },
  { id: 186, name: "Wedding Groomsmen Thank You Box", occasions: ["Wedding"], gender: "male", maxAge: 45, price: 59.99 },
  { id: 187, name: "Wedding Morning Prep Box for Her", occasions: ["Wedding"], gender: "female", maxAge: 45, price: 69.99 },
  { id: 188, name: "Wedding Morning Prep Box for Him", occasions: ["Wedding"], gender: "male", maxAge: 45, price: 69.99 },
  { id: 189, name: "Wedding Spa & Relaxation Box", occasions: ["Wedding","Anniversary"], gender: "unisex", maxAge: 99, price: 89.99 },
  { id: 190, name: "Wedding Keepsake & Memory Box", occasions: ["Wedding"], gender: "unisex", maxAge: 99, price: 79.99 },

  // Anniversary (191–200)
  { id: 191, name: "Anniversary Date Night Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 79.99 },
  { id: 192, name: "Anniversary Breakfast in Bed Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 193, name: "Anniversary Movie Night Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 194, name: "Anniversary Spa & Relax Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 84.99 },
  { id: 195, name: "Anniversary Wine & Cheese Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 89.99 },
  { id: 196, name: "Anniversary Coffee Lover Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 54.99 },
  { id: 197, name: "Anniversary Memory & Photo Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 74.99 },
  { id: 198, name: "Anniversary Luxury Night In Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 99.99 },
  { id: 199, name: "Anniversary Outdoor Picnic Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 84.99 },
  { id: 200, name: "Anniversary Sweet Treats Box", occasions: ["Anniversary"], gender: "unisex", maxAge: 99, price: 49.99 },

  // Retirement (201–210)
  { id: 201, name: "Retirement Relaxation Box", occasions: ["Retirement"], gender: "unisex", maxAge: 99, price: 79.99 },
  { id: 202, name: "Retirement Travel Dreams Box", occasions: ["Retirement"], gender: "unisex", maxAge: 99, price: 89.99 },
  { id: 203, name: "Retirement Coffee & Reading Box", occasions: ["Retirement"], gender: "unisex", maxAge: 99, price: 59.99 },
  { id: 204, name: "Retirement Hobby Starter Box", occasions: ["Retirement"], gender: "unisex", maxAge: 99, price: 69.99 },
  { id: 205, name: "Retirement Gourmet Snack Box", occasions: ["Retirement"], gender: "unisex", maxAge: 99, price: 64.99 },
  { id: 206, name: "Retirement Spa & Relax Box", occasions: ["Retirement"], gender: "unisex", maxAge: 99, price: 84.99 },
  { id: 207, name: "Retirement Golf Lover Box", occasions: ["Retirement"], gender: "male", maxAge: 99, price: 89.99 },
  { id: 208, name: "Retirement Garden Lover Box", occasions: ["Retirement"], gender: "unisex", maxAge: 99, price: 74.99 },
  { id: 209, name: "Retirement Office Farewell Box", occasions: ["Retirement"], gender: "unisex", maxAge: 99, price: 49.99 },
  { id: 210, name: "Retirement Cozy Home Box", occasions: ["Retirement"], gender: "unisex", maxAge: 99, price: 79.99 }

];

// END OF FILE — FULLY CLOSED, NO SYNTAX ERRORS
